import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const agents = [
  {
    email: 'john.smith@estate.com',
    name: 'John Smith',
    phone: '+1 (555) 123-4567',
    agency: 'Premium Realty',
    licenseNumber: 'RE12345',
    rating: 4.8,
    reviews: 24,
  },
  {
    email: 'sarah.jones@estate.com',
    name: 'Sarah Jones',
    phone: '+212 6 12 34 56 78',
    agency: 'Morocco Homes',
    licenseNumber: 'RE23456',
    rating: 4.9,
    reviews: 31,
  },
  {
    email: 'ahmed.bennani@estate.com',
    name: 'Ahmed Bennani',
    phone: '+212 6 98 76 54 32',
    agency: 'Moroccan Properties',
    licenseNumber: 'RE34567',
    rating: 4.7,
    reviews: 18,
  },
  {
    email: 'fatima.hassan@estate.com',
    name: 'Fatima Hassan',
    phone: '+212 6 55 44 33 22',
    agency: 'Casablanca Real Estate',
    licenseNumber: 'RE45678',
    rating: 4.9,
    reviews: 25,
  },
];

export const properties = [
  // ============ CASABLANCA (15 properties) ============
  {
    title: 'Luxury Apartment in Anfa',
    description: 'Modern 3-bedroom apartment with city views. Recently renovated with modern appliances, air conditioning, and a spacious living area.',
    price: 2500000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Anfa Boulevard',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5731,
    lng: -7.5898,
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    yearBuilt: 2018,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: 'Villa with Garden in Ain Diab',
    description: 'Spacious 4-bedroom villa near the beach. Features a beautiful garden, modern kitchen, swimming pool, and direct beach access.',
    price: 4200000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Ain Diab Beachfront',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5561,
    lng: -7.6391,
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    yearBuilt: 2012,
    parking: 2,
    furnished: false,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Studio in Downtown Casablanca',
    description: 'Compact and affordable studio apartment in city center. Perfect for young professionals. Furnished, air-conditioned, and close to shops.',
    price: 850000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Hassan II Street',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5731,
    lng: -7.5898,
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    yearBuilt: 2020,
    parking: 0,
    furnished: true,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1554995207-c18231b6ce48?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'Townhouse in Gauthier',
    description: 'Charming 3-level townhouse with modern design. Features elevator, security system, parking, and beautiful terrace.',
    price: 3100000,
    type: 'house' as const,
    status: 'sale' as const,
    address: 'Gauthier Residential',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5629,
    lng: -7.5876,
    bedrooms: 3,
    bathrooms: 2,
    area: 220,
    yearBuilt: 2019,
    parking: 1,
    furnished: false,
    balcony: true,
    garden: true,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78991c7c1da4?w=800',
      'https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'Penthouse in Sidi Maarouf',
    description: 'Ultra-modern penthouse with panoramic city and ocean views. Luxury finishes, smart home technology, spa, and exclusive amenities.',
    price: 5800000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Sidi Maarouf Tower',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5233,
    lng: -7.6702,
    bedrooms: 4,
    bathrooms: 3,
    area: 350,
    yearBuilt: 2021,
    parking: 2,
    furnished: true,
    balcony: true,
    garden: false,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f7c1ecdf?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: '2BR Apartment in Racine',
    description: 'Cozy 2-bedroom apartment in peaceful residential area. Modern furnishings, balcony with garden view, central air conditioning.',
    price: 1200000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Racine District',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5845,
    lng: -7.5823,
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    yearBuilt: 2017,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Luxury Villa in Ain Sebaa',
    description: 'Premium 5-bedroom villa with full amenities. Includes tennis court, Olympic pool, lush gardens, and 24/7 security.',
    price: 6500000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Ain Sebaa Gardens',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5515,
    lng: -7.4847,
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    yearBuilt: 2010,
    parking: 3,
    furnished: false,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: '1BR Apartment Downtown',
    description: 'Affordable 1-bedroom apartment in business district. Perfect for professionals. Modern, secure building with good parking facilities.',
    price: 650000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Business District',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5731,
    lng: -7.5898,
    bedrooms: 1,
    bathrooms: 1,
    area: 50,
    yearBuilt: 2019,
    parking: 1,
    furnished: false,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1554995207-c18231b6ce48?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: '3BR Villa in Oasis',
    description: 'Beautiful villa in gated community. Features pool, garden, modern kitchen, and 24/7 gated security.',
    price: 3800000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Oasis Community',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.4987,
    lng: -7.5654,
    bedrooms: 3,
    bathrooms: 2,
    area: 300,
    yearBuilt: 2016,
    parking: 2,
    furnished: false,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
      'https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: '2BR Apartment in Maârif',
    description: 'Modern apartment in trendy neighborhood. Balcony, air conditioning, furnished, close to restaurants and shopping.',
    price: 1550000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Maârif Avenue',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5504,
    lng: -7.5965,
    bedrooms: 2,
    bathrooms: 1,
    area: 100,
    yearBuilt: 2020,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Beachfront Apartment',
    description: 'Stunning apartment with direct ocean view. 3 bedrooms, modern kitchen, access to private beach.',
    price: 3200000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Ain Diab Beach',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5561,
    lng: -7.6391,
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    yearBuilt: 2018,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'Commercial Space',
    description: 'Prime location retail/office space. Street level, high foot traffic, perfect for business ventures.',
    price: 2800000,
    type: 'commercial' as const,
    status: 'sale' as const,
    address: 'Hassan II Center',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5731,
    lng: -7.5898,
    bedrooms: 0,
    bathrooms: 2,
    area: 200,
    yearBuilt: 2015,
    parking: 2,
    furnished: false,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'Duplex in Elbiad',
    description: 'Spacious duplex with garden in quiet residential area. Modern finishes, parking, perfect for families.',
    price: 2100000,
    type: 'house' as const,
    status: 'sale' as const,
    address: 'Elbiad District',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5876,
    lng: -7.5643,
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    yearBuilt: 2017,
    parking: 1,
    furnished: false,
    balcony: true,
    garden: true,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78991c7c1da4?w=800',
      'https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: 'Studio in Nouvelle Medina',
    description: 'Budget-friendly studio in peaceful neighborhood. Basic amenities, quiet area, good for first-time buyers.',
    price: 550000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Nouvelle Medina',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5612,
    lng: -7.5543,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    yearBuilt: 2014,
    parking: 0,
    furnished: false,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1554995207-c18231b6ce48?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: '4BR House in Sefrou',
    description: 'Traditional Moroccan house with modern updates. Courtyard, parking, recently renovated, authentic charm.',
    price: 1800000,
    type: 'house' as const,
    status: 'sale' as const,
    address: 'Sefrou Medina',
    city: 'Casablanca',
    state: 'Casablanca-Settat',
    zipCode: '20000',
    country: 'Morocco',
    lat: 33.5423,
    lng: -7.6234,
    bedrooms: 4,
    bathrooms: 2,
    area: 250,
    yearBuilt: 2008,
    parking: 1,
    furnished: false,
    balcony: false,
    garden: true,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },

  // ============ MARRAKECH (10 properties) ============
  {
    title: 'Riad in Medina',
    description: 'Traditional riad with modern amenities in heart of medina. Central courtyard, rooftop terrace, authentic Moroccan design.',
    price: 2800000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Medina Center',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6295,
    lng: -7.9811,
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    yearBuilt: 2010,
    parking: 0,
    furnished: true,
    balcony: false,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'Luxury Villa in Palmeraie',
    description: 'Exclusive villa in Palmeraie resort with golf course access. Spa, large pool, lush gardens, ultimate luxury.',
    price: 8500000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Palmeraie Golf Resort',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6872,
    lng: -7.9956,
    bedrooms: 5,
    bathrooms: 4,
    area: 600,
    yearBuilt: 2012,
    parking: 3,
    furnished: true,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: 'Apartment near Jemaa el-Fnaa',
    description: 'Central location near famous square. 2 bedrooms, furnished, air-conditioned, great for tourism investment.',
    price: 1500000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Jemaa el-Fnaa',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6295,
    lng: -7.9811,
    bedrooms: 2,
    bathrooms: 1,
    area: 90,
    yearBuilt: 2018,
    parking: 0,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Modern Villa in Hivernage',
    description: 'Contemporary villa with pool and modern amenities. Beautiful garden, perfect for families, good location.',
    price: 4500000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Hivernage District',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6408,
    lng: -7.9813,
    bedrooms: 3,
    bathrooms: 3,
    area: 320,
    yearBuilt: 2019,
    parking: 2,
    furnished: false,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
      'https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'Studio in Ville Nouvelle',
    description: 'Modern studio in new town area. Affordable, furnished, good for young professionals and students.',
    price: 700000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Ville Nouvelle',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6295,
    lng: -8.0089,
    bedrooms: 1,
    bathrooms: 1,
    area: 50,
    yearBuilt: 2020,
    parking: 0,
    furnished: true,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1554995207-c18231b6ce48?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'Boutique Riad Hotel',
    description: 'Operating riad hotel with rental income potential. 6 bedrooms, restaurant, rooftop terrace, business ready.',
    price: 5200000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Kasbah Area',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6088,
    lng: -7.9734,
    bedrooms: 6,
    bathrooms: 5,
    area: 400,
    yearBuilt: 2008,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: 'Apartment with Atlas View',
    description: 'Beautiful apartment with mountain views. Modern, 3 bedrooms, balcony, great natural surroundings.',
    price: 2000000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Atlas Side',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6295,
    lng: -7.9811,
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    yearBuilt: 2017,
    parking: 1,
    furnished: false,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'House in Douar Lhna',
    description: 'Spacious family home in quiet area. 4 bedrooms, garden, traditional design, good value.',
    price: 1200000,
    type: 'house' as const,
    status: 'sale' as const,
    address: 'Douar Lhna',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.5987,
    lng: -7.9854,
    bedrooms: 4,
    bathrooms: 2,
    area: 280,
    yearBuilt: 2009,
    parking: 1,
    furnished: false,
    balcony: false,
    garden: true,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'Penthouse in Hivernage',
    description: 'Luxurious penthouse with terraces and pool access. Modern finishes, great amenities, premium location.',
    price: 3800000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Hivernage Tower',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6408,
    lng: -7.9813,
    bedrooms: 3,
    bathrooms: 2,
    area: 220,
    yearBuilt: 2020,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f7c1ecdf?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'Land Plot in Palmeraie',
    description: 'Prime land for development. Infrastructure ready, development potential, strategic location.',
    price: 3200000,
    type: 'land' as const,
    status: 'sale' as const,
    address: 'Palmeraie',
    city: 'Marrakech',
    state: 'Marrakech-Safi',
    zipCode: '40000',
    country: 'Morocco',
    lat: 31.6872,
    lng: -7.9956,
    bedrooms: 0,
    bathrooms: 0,
    area: 1000,
    yearBuilt: 2000,
    parking: 0,
    furnished: false,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1500595046891-a6d050a71f47?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },

  // ============ FES (8 properties) ============
  {
    title: 'Dar in Medina',
    description: 'Traditional Moroccan house in historic medina. Renovated courtyard, authentic design, cultural value.',
    price: 1400000,
    type: 'house' as const,
    status: 'sale' as const,
    address: 'Medina Old City',
    city: 'Fes',
    state: 'Fes-Meknes',
    zipCode: '30000',
    country: 'Morocco',
    lat: 34.0612,
    lng: -4.9704,
    bedrooms: 4,
    bathrooms: 2,
    area: 220,
    yearBuilt: 1995,
    parking: 0,
    furnished: false,
    balcony: false,
    garden: true,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Apartment in Nouvelle Ville',
    description: 'Modern apartment in new town. Contemporary design, air conditioning, convenient location.',
    price: 950000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Nouvelle Ville',
    city: 'Fes',
    state: 'Fes-Meknes',
    zipCode: '30000',
    country: 'Morocco',
    lat: 34.0708,
    lng: -4.9904,
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    yearBuilt: 2019,
    parking: 1,
    furnished: false,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'Villa with Garden',
    description: 'Spacious villa outside medina with beautiful garden. Pool, parking, modern amenities.',
    price: 2200000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Zaouia District',
    city: 'Fes',
    state: 'Fes-Meknes',
    zipCode: '30000',
    country: 'Morocco',
    lat: 34.0444,
    lng: -4.9876,
    bedrooms: 3,
    bathrooms: 2,
    area: 250,
    yearBuilt: 2013,
    parking: 1,
    furnished: false,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'Studio Downtown',
    description: 'Affordable studio in city center. Budget-friendly, furnished, great location for business.',
    price: 600000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Downtown Fes',
    city: 'Fes',
    state: 'Fes-Meknes',
    zipCode: '30000',
    country: 'Morocco',
    lat: 34.0612,
    lng: -4.9704,
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    yearBuilt: 2015,
    parking: 0,
    furnished: true,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1554995207-c18231b6ce48?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: 'House near University',
    description: 'Ideal for students and academics. 3 bedrooms, furnished, near university campus.',
    price: 800000,
    type: 'house' as const,
    status: 'sale' as const,
    address: 'University Area',
    city: 'Fes',
    state: 'Fes-Meknes',
    zipCode: '30000',
    country: 'Morocco',
    lat: 34.0054,
    lng: -5.0056,
    bedrooms: 3,
    bathrooms: 1,
    area: 150,
    yearBuilt: 2011,
    parking: 0,
    furnished: true,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Apartment with City View',
    description: 'Modern apartment with great city views. Contemporary design, 2 bedrooms, furnished.',
    price: 1300000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Ville Nouvelle Heights',
    city: 'Fes',
    state: 'Fes-Meknes',
    zipCode: '30000',
    country: 'Morocco',
    lat: 34.0708,
    lng: -4.9904,
    bedrooms: 2,
    bathrooms: 1,
    area: 100,
    yearBuilt: 2020,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'Commercial Shop',
    description: 'Retail space in busy area. Street level, high traffic, excellent for commerce.',
    price: 1100000,
    type: 'commercial' as const,
    status: 'sale' as const,
    address: 'Tarik Jdid',
    city: 'Fes',
    state: 'Fes-Meknes',
    zipCode: '30000',
    country: 'Morocco',
    lat: 34.0529,
    lng: -4.9654,
    bedrooms: 0,
    bathrooms: 1,
    area: 80,
    yearBuilt: 2014,
    parking: 0,
    furnished: false,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'Traditional Riad',
    description: 'Beautiful restored riad with traditional design. Central courtyard, rooftop, cultural heritage.',
    price: 2800000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Medina Heritage',
    city: 'Fes',
    state: 'Fes-Meknes',
    zipCode: '30000',
    country: 'Morocco',
    lat: 34.0612,
    lng: -4.9704,
    bedrooms: 5,
    bathrooms: 3,
    area: 300,
    yearBuilt: 1990,
    parking: 0,
    furnished: false,
    balcony: false,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },

  // ============ TANGIER (7 properties) ============
  {
    title: 'Beachfront Villa',
    description: 'Stunning villa with direct beach access. 4 bedrooms, pool, modern design, sea views.',
    price: 3500000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Tangier Beach',
    city: 'Tangier',
    state: 'Tanger-Tetouan',
    zipCode: '90000',
    country: 'Morocco',
    lat: 35.7595,
    lng: -5.8330,
    bedrooms: 4,
    bathrooms: 3,
    area: 300,
    yearBuilt: 2018,
    parking: 2,
    furnished: true,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Apartment in Medina',
    description: 'Central location in historic medina. Traditional design, 2 bedrooms, cultural area.',
    price: 1100000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Medina Old City',
    city: 'Tangier',
    state: 'Tanger-Tetouan',
    zipCode: '90000',
    country: 'Morocco',
    lat: 35.7671,
    lng: -5.8036,
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    yearBuilt: 2005,
    parking: 0,
    furnished: false,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'Modern Apartment Downtown',
    description: 'Contemporary apartment in city center. Modern amenities, parking, good location.',
    price: 1400000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Downtown Tangier',
    city: 'Tangier',
    state: 'Tanger-Tetouan',
    zipCode: '90000',
    country: 'Morocco',
    lat: 35.7733,
    lng: -5.8067,
    bedrooms: 2,
    bathrooms: 1,
    area: 95,
    yearBuilt: 2019,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'House with Garden',
    description: 'Family home with outdoor space. 4 bedrooms, garden, parking, modern conveniences.',
    price: 2100000,
    type: 'house' as const,
    status: 'sale' as const,
    address: 'Ville Nouvelle',
    city: 'Tangier',
    state: 'Tanger-Tetouan',
    zipCode: '90000',
    country: 'Morocco',
    lat: 35.7688,
    lng: -5.8120,
    bedrooms: 4,
    bathrooms: 2,
    area: 280,
    yearBuilt: 2016,
    parking: 1,
    furnished: false,
    balcony: true,
    garden: true,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: 'Studio near Port',
    description: 'Budget option near harbor. Studio apartment, affordable, close to sea.',
    price: 700000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Port Area',
    city: 'Tangier',
    state: 'Tanger-Tetouan',
    zipCode: '90000',
    country: 'Morocco',
    lat: 35.7779,
    lng: -5.8067,
    bedrooms: 1,
    bathrooms: 1,
    area: 50,
    yearBuilt: 2014,
    parking: 0,
    furnished: true,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1554995207-c18231b6ce48?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Penthouse with Sea View',
    description: 'Luxury penthouse overlooking the sea. Modern, high-end finishes, exclusive.',
    price: 2800000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Malabata Heights',
    city: 'Tangier',
    state: 'Tanger-Tetouan',
    zipCode: '90000',
    country: 'Morocco',
    lat: 35.7458,
    lng: -5.8276,
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    yearBuilt: 2020,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f7c1ecdf?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'Land near City Center',
    description: 'Prime development land in strategic location. Ready for development projects.',
    price: 2300000,
    type: 'land' as const,
    status: 'sale' as const,
    address: 'City Center',
    city: 'Tangier',
    state: 'Tanger-Tetouan',
    zipCode: '90000',
    country: 'Morocco',
    lat: 35.7733,
    lng: -5.8067,
    bedrooms: 0,
    bathrooms: 0,
    area: 800,
    yearBuilt: 2000,
    parking: 0,
    furnished: false,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1500595046891-a6d050a71f47?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },

  // ============ RABAT (6 properties) ============
  {
    title: 'Apartment in Agdal',
    description: 'Modern apartment in upscale neighborhood. 3 bedrooms, parking, contemporary design.',
    price: 2000000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Agdal District',
    city: 'Rabat',
    state: 'Rabat-Sale-Kenitra',
    zipCode: '10000',
    country: 'Morocco',
    lat: 34.0209,
    lng: -6.8416,
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    yearBuilt: 2017,
    parking: 1,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: 'Villa in Ocean',
    description: 'Luxurious villa in exclusive area. 4 bedrooms, pool, garden, premium location.',
    price: 3800000,
    type: 'villa' as const,
    status: 'sale' as const,
    address: 'Ocean District',
    city: 'Rabat',
    state: 'Rabat-Sale-Kenitra',
    zipCode: '10000',
    country: 'Morocco',
    lat: 34.0098,
    lng: -6.8376,
    bedrooms: 4,
    bathrooms: 3,
    area: 350,
    yearBuilt: 2016,
    parking: 2,
    furnished: false,
    balcony: true,
    garden: true,
    pool: true,
    images: [
      'https://images.unsplash.com/photo-1613228060223-461bea69b13a?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
  {
    title: 'Apartment near Hassan Tower',
    description: 'Tourist area apartment with cultural significance. 2 bedrooms, furnished, modern.',
    price: 1500000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Hassan Tower Area',
    city: 'Rabat',
    state: 'Rabat-Sale-Kenitra',
    zipCode: '10000',
    country: 'Morocco',
    lat: 34.0180,
    lng: -6.8128,
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    yearBuilt: 2019,
    parking: 0,
    furnished: true,
    balcony: true,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    agentEmail: 'ahmed.bennani@estate.com',
  },
  {
    title: 'House in Souissi',
    description: 'Spacious family home with modern kitchen. 5 bedrooms, garden, premium district.',
    price: 2800000,
    type: 'house' as const,
    status: 'sale' as const,
    address: 'Souissi',
    city: 'Rabat',
    state: 'Rabat-Sale-Kenitra',
    zipCode: '10000',
    country: 'Morocco',
    lat: 34.0436,
    lng: -6.8293,
    bedrooms: 5,
    bathrooms: 3,
    area: 350,
    yearBuilt: 2012,
    parking: 2,
    furnished: false,
    balcony: true,
    garden: true,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f41b3883?w=800',
    ],
    agentEmail: 'fatima.hassan@estate.com',
  },
  {
    title: 'Studio in Medina',
    description: 'Historic medina studio. Budget-friendly, authentic, cultural area.',
    price: 650000,
    type: 'apartment' as const,
    status: 'sale' as const,
    address: 'Medina Rabat',
    city: 'Rabat',
    state: 'Rabat-Sale-Kenitra',
    zipCode: '10000',
    country: 'Morocco',
    lat: 34.0224,
    lng: -6.8344,
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    yearBuilt: 2010,
    parking: 0,
    furnished: false,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1554995207-c18231b6ce48?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    agentEmail: 'john.smith@estate.com',
  },
  {
    title: 'Commercial Office',
    description: 'Modern office space in business district. Professional, well-equipped, ready for use.',
    price: 1800000,
    type: 'commercial' as const,
    status: 'sale' as const,
    address: 'Business District',
    city: 'Rabat',
    state: 'Rabat-Sale-Kenitra',
    zipCode: '10000',
    country: 'Morocco',
    lat: 34.0209,
    lng: -6.8416,
    bedrooms: 0,
    bathrooms: 2,
    area: 150,
    yearBuilt: 2018,
    parking: 2,
    furnished: true,
    balcony: false,
    garden: false,
    pool: false,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    ],
    agentEmail: 'sarah.jones@estate.com',
  },
]

async function main() {
  const passwordHash = await bcrypt.hash('password123', 10);

  await prisma.property.deleteMany();
  await prisma.user.deleteMany();

  const agentMap = new Map<string, string>();

  for (const agent of agents) {
    const user = await prisma.user.create({
      data: {
        email: agent.email,
        passwordHash,
        name: agent.name,
        role: 'agent',
        phone: agent.phone,
        agency: agent.agency,
        licenseNumber: agent.licenseNumber,
        rating: agent.rating,
        reviews: agent.reviews,
      },
    });
    agentMap.set(agent.email, user.id);
  }

  for (const p of properties) {
    const agentId = agentMap.get(p.agentEmail);
    if (!agentId) continue;

    const { agentEmail: _ae, images, ...data } = p;
    await prisma.property.create({
      // cast to any to satisfy Prisma Client's generated types for enums
      data: {
        ...(data as any),
        images: JSON.stringify(images),
        agentId,
      } as any,
    });
  }

  console.log('Seeded 3 agents and 6 properties (password: password123)');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
